### PR TITLE
Implement dataset 2467

### PR DESCRIPTION
**Pull request by nico-arnold**
Split PR for the dataset 2467 support. Do you want me to include the testing here or better in a new PR? If latter, please just merge this one, and I will create a new one then for the testing. Otherwise, just let me know and I will include everything here.

### CODE REVIEW

**Comment by jankoslavic** [comment]
@nico-arnold thanks. Can you help me finding the specification for this dataset? I cannot find it at: https://www.ceas3.uc.edu/sdrluff/all_files.php

**Comment by nico-arnold** [comment]
@jankoslavic you're welcome! The official one is down, sadly. But there is a copy in the comments of this implementation here: https://github.com/victorsndvg/FEconv/blob/master/source/unv/module_dataset_2467.f90

**Comment by nico-arnold** [comment]
@jankoslavic Sure, no problem, will do. I also saw that you indeed had another implementation for the 2429 group format; I will change the index names to the one you used there, okay?
The commit looks good, I will test it the next days when I have some free time.

**Comment by jankoslavic** [comment]
Thank you @nico-arnold ! Sounds good

**Comment by nico-arnold** [comment]
PR updated and ready to merge (:
Testcase (prepare, read, write) up and running.
I also adapted the way to rad and write the dataset to the one you used in your dataset 2429 implementation.

**Comment by jankoslavic** [comment]
@nico-arnold this looks very good. I have made some polishing (the whole package uses single quotes) and slightly modified the testing. Please double-check. I am prepared to merge (if you confirm)

**Comment by nico-arnold** [comment]
Ah, I totally forgot about the double quotes, thanks for correcting. Looks good to me! Tests also run through perfectly, should be fine to merge I think.

**Comment by jankoslavic** [comment]
@nico-arnold thank you also for this!!!

**Pull request merged**
