### PR TITLE
Bugfix writing 2414

### PR DESCRIPTION
**Pull request by toonijn**
This fixes a bug on writing dataset 2414.

### CODE REVIEW

**Comment by jankoslavic** [comment]
Thank you @toonijn. It looks simple, but I would like to ask @michaelquaglia for a comment as he initially coded this dataset.

**Comment by jankoslavic** [comment]
We would also need a test for this. @toonijn could you doit?

**Comment by michaelquaglia** [comment]
@jankoslavic I only used 2414/analysis_type = 5 on my side so I could not test the fix. I would also like to say that I did not initially coded this dataset but expanded it for 1 and 2D input data :). Previously it was only working for 3D data.
Thanks a lot @toonijn

**Comment by jankoslavic** [comment]
Thank you @michaelquaglia . Anyway, @toonijn we need a test for this. I would start with the file where you observed the problem (probably the dataset can be shortened).
If you need help, please let me know.

**Comment by toonijn** [comment]
No problem!

I've added a test with a small part of the file where it went wrong.

**Comment by jankoslavic** [comment]
Thanks! I have made a double check. Everything looks fine for me. Thank you @toonijn !!!

**Pull request merged**
