### PR TITLE
Restructured package

### PR DESCRIPTION
**Pull request by klemengit**
The package has been restructured to exclude the read/write functions for specific datasets from the main ``UFF`` class. Also, the ``tools.py`` module was added that contains the helper functions.

The new, proposed structure of the package is:
* data
* docs
* tests
* pyuff
    * datasets
        * dataset_15.py
        * dataset_55.py
        * ...
    * pyuff.py
    * tools.py

### CODE REVIEW

**Comment by jankoslavic** [comment]
I guess we could also remove UFFException in the tools. What do you think @klemengit ?

**Comment by klemengit** [comment]
We could probably remove the exception as it is only a thin wrapper..

I will also take a look why the tests have failed, locally all the test have passed.

**Comment by jankoslavic** [comment]
I would suggest moving the "prepare_test_x" to separate files in the datasets folder.

**Comment by klemengit** [comment]
I agree. I'll move the functions.

**Pull request merged**
