### PR TITLE
Added function to convert set 2412 to set 82

### PR DESCRIPTION
**Pull request by zinebzahar1997**
+  function to convert set 2412 to set 82 " pyuff/datasets/convert_dataset_2412_to_82.py"
+ " tests/test_convert_2412_to_82.py" to validate the function 
+ reference files in  "data/"

### CODE REVIEW

**Comment by jankoslavic** [comment]
@zinebzahar1997 thank you for the  PR. It looks like a good start. The PR is very big and includes too many changes at once. I would need your help to accept this PR. First, I would ask you to separate the formatting issue to other issues. Formatting: pyUFF uses single quotes `'` and not double quotes `"`. If you would like to propose this change, please open a separate PR, but I first suggest opening an issue where users will discuss this change. Changes to datasets 15 and 82 should be in a separate PR and it should be clear why these changes are required. Convert function should be a separate PR with provided tests.

**Comment by zinebzahar1997** [comment]
@jankoslavic thank you for these details, Actually the main change I included is convert function. I will make a clearer PR !

**Comment by zinebzahar1997** [comment]
@jankoslavic in my last commit I reverted the changes concerning formatting issue and datasets 15 and 82 to keep only convert function which enables conversion from set 2412 to set 82 with its validation test and .unv test file, is it clearer ?

**Comment by jankoslavic** [comment]
Dear @zinebzahar1997 thank you for your effort. I would suggest closing this PR and then opening up a new PR for data type 15 corrections. One PR for 82 corrections and the final for the conversion from 2412 to 82. Would this go with you? I this way it will be much easier to maintain. Thank you

**Comment by zinebzahar1997** [comment]
Hello @jankoslavic, thank you for your answer. I suggest to make only the PR on conversion from set 2412 to set 82 for now as the changes on data sets 15 and 82 are only about single or double quote. Is it fine this way ?

**Comment by jankoslavic** [comment]
@zinebzahar1997 yes, this would be great

**Pull request closed without merging**
