### PR TITLE
read_sets() without loading data

### PR DESCRIPTION
**Pull request by jlmoreno93**
Hi. I modified read_sets(), _read_set() and _extract58() to give option to load metadata only (for dataset 58). I am not as familiar with the other datasets so I didnt add the functionality to them. default is to load all datasets as normal for backwards compatibility.
 
Thanks,

### CODE REVIEW

**Comment by jankoslavic** [comment]
thank you @jlmoreno93, please give me some time to check the details.

**Comment by jankoslavic** [comment]
Dear @jlmoreno93 in general it looks ok to me. I would however prefer to have the parameter `header_only`=False by default instead of `include_all`. I think the parameter would be more clear in this case. How does that sound to you?

**Comment by jlmoreno93** [comment]
I agree, I like that better! should I modify it?

**Comment by jankoslavic** [comment]
Yes, please. This would be great!

**Comment by jankoslavic** [comment]
I added some polishing and a test; before I merge it, I ask you for a double-check

**Comment by jlmoreno93** [comment]
@jankoslavic I am probably not qualified to check your work as I am still learning, but I did review it and the changes you made make sense to me.

**Comment by jankoslavic** [comment]
@jlmoreno93 thank you and congratulations on your first PR to pyUFF!

**Pull request merged**
